import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "COD Network",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-zinc-800`}>
        {/* Start Navbar */}
        <nav className="p-4">
          <div className="container mx-auto flex items-center justify-between">
            <a href="#" className="text-white text-xl font-bold">
              COD Network
            </a>

            <div className="space-x-4">
              <a href="#" className="text-white">
                Multiplayer
              </a>
              <a href="#" className="text-white">
                Zombies
              </a>
            </div>

            <div className="text-transparent select-none">kanker aap negro</div>
          </div>
        </nav>

        {children}

        {/* Start Footer */}
        <footer className="text-white p-4 mt-auto">
          <div className="container mx-auto text-center">
            <p>&copy; 2023 COD Network. All rights reserved.</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
